FROM python:3.6
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get install -y nodejs
# confirm installation
RUN node -v
RUN npm -v
RUN npm i npm@latest -g
RUN npm i -g @angular/cli
WORKDIR /src/client
